# Generated by Django 5.0.6 on 2024-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto_profilo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Editori',
            },
        ),
        migrations.CreateModel(
            name='Sviluppatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto_profilo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Sviluppatori',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto_profilo', models.ImageField(upload_to='')),
                ('biografia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
    ]
