# Generated by Django 5.0.6 on 2024-06-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirente',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='acquirente',
            name='foto_profilo',
            field=models.ImageField(default='imgs/default_profile_image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='venditore',
            name='foto_profilo',
            field=models.ImageField(default='imgs/default_profile_image.png', upload_to=''),
        ),
    ]
