# Generated by Django 5.0.6 on 2024-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0004_alter_acquirente_foto_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirente',
            name='foto_profilo',
            field=models.ImageField(default='imgs/default_profile_image.png', upload_to='media/profile_pics/'),
        ),
    ]
