# Generated by Django 5.0.6 on 2024-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0006_alter_acquirente_foto_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirente',
            name='foto_profilo',
            field=models.ImageField(default='media/imgs/default_profile_image.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='venditore',
            name='foto_profilo',
            field=models.ImageField(default='media/imgs/default_profile_image.png', upload_to='profile_pics/'),
        ),
    ]
