# Generated by Django 5.0.6 on 2024-06-27 09:02

import utenti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0008_alter_acquirente_foto_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, validators=[utenti.models.MyValidator()], verbose_name='username'),
        ),
    ]
