# Generated by Django 5.0.6 on 2024-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquirente',
            name='oscurato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venditore',
            name='oscurato',
            field=models.BooleanField(default=False),
        ),
    ]
