# Generated by Django 5.0.6 on 2024-06-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domanda',
            options={'verbose_name_plural': 'Domande'},
        ),
        migrations.AlterModelOptions(
            name='immagine',
            options={'verbose_name_plural': 'Immagini'},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name_plural': 'Recensioni'},
        ),
    ]
