# Generated by Django 5.0.6 on 2024-06-23 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0002_alter_domanda_risposta_alter_domanda_utente_risposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagine',
            name='img',
            field=models.ImageField(default='imgs/placeholder_image.png', upload_to='game-images/'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
