# Generated by Django 5.0.6 on 2024-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0003_alter_immagine_img_alter_prodotto_prezzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagine',
            name='img',
            field=models.ImageField(default='imgs/placeholder_image.png', upload_to='game_images/'),
        ),
    ]
