# Generated by Django 5.0.6 on 2024-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0004_alter_immagine_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(default='imgs/placeholder_image.png', upload_to='game_images/'),
        ),
        migrations.DeleteModel(
            name='Immagine',
        ),
    ]
