# Generated by Django 5.0.6 on 2024-06-30 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0005_prodotto_immagine_delete_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='oscurato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='oscurato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recensione',
            name='oscurato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='voto',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
